### PR TITLE
Userrights function

### PR DESCRIPTION
**Pull request by mezianeAITE**
Adding userrights basic managment

### CODE REVIEW

**Comment by mezianeAITE** [comment]
It's a basic userrights management. It can be improved by adding exception when:
- User can't change rights
- group doesn't exist.
But it work well when it's not the case.

**Comment by Gelbpunkt** [comment]
There's one thing I'd love you to do: please run black on it (`pip install black && black .`) and push again. It's the code formatter I'm using.

I'll comment on lines I would like to see different

**Comment by mezianeAITE** [comment]
Ok i will do it, i just have a deadline for a project this end of week. But it's on my todo list ;)

**Comment by Gelbpunkt** [comment]
Sure, no pressure. If you feel too busy, I can do these changes instead

**Comment by mezianeAITE** [comment]
Hi,
I almost done the error handling:
1. When user doesn't exist: 
json = {'error': {'code': 'nosuchuser', 'info': 'There is no user by the name "XXX". Check your spelling.', '*': 'See XXX/api.php for API usage.'}}
I raise a new error NoSuchUserError
2. When the group in which we want to add/remove user doesn't exist:
json = {'warnings': {'userrights': {'*': 'Unrecognized value for parameter "add": test.'}}

But i have a tricky case:
let say i a want to add user 'test' to the group 'bureaucrat':
When user used to create session have the right to edit other user rights:
if 'test' is not in 'bureaucrat':
json = {'userrights': {'user': 'XXX', 'userid': 42, 'added': ['bureaucrat'], 'removed': []}}
else:
json = {'userrights': {'user': 'XXX', 'userid': 42, 'added': [], 'removed': []}}

When user used to create session doesn't have the right to edit other user rights:
if 'test' is OR is not in 'bureaucrat':
json = {'userrights': {'user': 'XXX', 'userid': 42, 'added': [], 'removed': []}}

What is the best way to handle this case ?

**Comment by Gelbpunkt** [comment]
For now, we cannot determine this without making a call to get user permissions before adding, which I don't like. I'd for now just act as it would have worked in all 3 cases you showed. For the future, I think best is having user objects that hold their own permissions value and we can allow things like this:

```py
await wiki.login("name", "password") # this sets the wiki._user and fetches permissions once
target_user = await wiki.get_user("name") # a new user object
await target_user.add_roles("bureaucrat") # add some roles. Throws permissions error if wiki._user doesn't have rights to do so
```

I'm fine with the current solution you made. Just commit and I'll merge it, the new User object will be something I can do in the next weeks.

**Comment by Gelbpunkt** [comment]
Would you mind removing the print calls? I'll merge and clean up the rest later

**Comment by Gelbpunkt** [comment]
Woo thanks a bunch :)

**Comment by mezianeAITE** [comment]
So i made i quick fix to handle the last case with the UserRightNotChangedError.
Thanks again for all your help !

**Pull request merged**
